name: kittentts_flutter_benchmark_app
description: KittenTTS Flutter benchmark app for TestMu CI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  kittentts_flutter:
    path: ../..
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cephonemizer/en_rules
    - assets/cephonemizer/en_list
    - assets/models/kitten-tts-nano-0.8/
    - assets/models/kitten-tts-nano-0.8-int8/
    - assets/models/kitten-tts-micro-0.8/
    - assets/models/kitten-tts-mini-0.8/
